### ISSUE TITLE
question: Some Logs lines are skipped

### ISSUE THREAD

**Issue by saurbkumar** [aigan/tail-file#2]
I am trying to read logs file with the below format:
2019-11-12 22:59:50, Some Event 7 
2019-11-12 23:10:51, Some Event 8
2019-11-12 23:20:52, Some Event 9 
2019-11-12 23:20:52, Some Event 10
2019-11-12 23:20:52, Some Event 11
2019-11-12 23:20:52, Some Event 12 
2019-11-12 23:20:52, Some Event 13 

with the following code:
```
var Tail = require("tail-file");
var mytail = new Tail("files/log", {
  force: true,
  secondary: ["files/log.1", "files/log.2"]
});

var referenceTime = "2019-11-12 23:10:51";
function comparator(data) {
  let result = 0;
  if (Date.parse(referenceTime) < Date.parse(data)) {
    result = -1;
  } else if (Date.parse(referenceTime) > Date.parse(data)) {
    result = 1;
  } else {
    result = 0;
  }
  return result;
}
async function findStart() {
  try {
    await mytail.findStart(/^(\d+-\d+-\d+ \d+:\d+:\d+)/, comparator);
    return true;
  } catch (error) {
    return false;
  }
}
(async () => {
  try {
    await findStart();
  } catch (error) {
    console.log("Error Occurred" + error);
  }
  mytail.on("line", line => {
    console.log("--line--found-- " + line);
  });
})();
```
The output is:
--line--found-- 2019-11-12 23:20:52, Some Event 10
--line--found-- 2019-11-12 23:20:52, Some Event 11
--line--found-- 2019-11-12 23:20:52, Some Event 12

but it should also print line:
**--line--found-- 2019-11-12 23:20:52, Some Event 9**
**--line--found-- 2019-11-12 23:20:52, Some Event 13**
Why these two line are skipped ? Is something wrong with the comparator function?

**Comment by aigan** [comment]
I'm sorry for the wait.
You should set up the line handler BEFORE finding the start. You missed some events.
