### ISSUE TITLE
[Feature Request] watch files by wildcard?

### ISSUE THREAD

**Issue by wizzard0** [aigan/tail-file#3]
**Scenario:** There are apps that create a file with different filename each time the app runs, e.g. when there could be multiple instances working in parallel.
**Example:** log-DATETIME.txt, log-PID.txt etc

**Suggestion:** 
1) Allow to watch filenames by glob pattern
2) An option to choose between tailing multiple filenames matching the pattern concurrently or just the last modified one (concurrent tailing obviously conflicts with logrotate feature though)
3) Expose the filename in event handlers

**Comment by aigan** [comment]
Sorry about late response.
I think this would introduce unnecessary additional complexity.
tail-file is built for easy modification or extension. Create a wrapper or subclass or just something like this;
```
const tail = new Tail();
tail.filename = find_the_logfile();
tail.start();
```
